### ISSUE TITLE
HAHA

### ISSUE THREAD

**Issue by KenMizz** [byteandahalf/modpe_ios#1]
lol

**Comment by byteandahalf** [comment]
Hi, please use the issue tracker to notify me of any bugs or issues otherwise that you are having with this tweak. Thank you for your input.

**Comment by officialmcpro32** [comment]
How would this work? Are you going to make a block launcher like app

**Comment by byteandahalf** [comment]
No, it runs standalone because it's a Cydia tweak

**Comment by enoter** [comment]
You will update GalactiCraft addon?

**Comment by Izaac9236** [comment]
*----------* ModPE in Iphone 0.14.0>0.15.0>0.16.0>0.17....0.99.0>1.0 ;------;
