### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by Thunder33345** [byteandahalf/modpe_ios#3]
how to compile it?

**Comment by byteandahalf** [comment]
Technically you don't yet, as I have yet to create a Makefile. However, you could hack it a bit and it runs on Windows

**Comment by byteandahalf** [comment]
If you change MSInitialize to int main() and change path in runTestScript() to a Windows path, you can build it with basic g++ commands

**Comment by Thunder33345** [comment]
no?
run compile it and run it on my linux ipad

**Comment by officialmcpro32** [comment]
@byteandahalf can I compile this on AIDE?

**Comment by byteandahalf** [comment]
No, it's not an Android app.

**Comment by officialmcpro32** [comment]
*isoundlikeadumblol ok thanks do you know any compiler for Android that can compile it

**Comment by byteandahalf** [comment]
no. You need to build on Linux, iOS, or Mac

**Comment by officialmcpro32** [comment]
Aww I can't use it *cries

**Comment by byteandahalf** [comment]
Don't worry, it doesn't work anyway.

**Comment by officialmcpro32** [comment]
But once it's done will android scripts work on it?

**Comment by TrinityDevelopers** [comment]
no even when its many done many android scripts will not work, especially the ones with GUI as they use Android OS code not found in IOS

**Comment by byteandahalf** [comment]
Actually, Zhuowei and I are discussing a common API for rendering native MCPE UI.

**Comment by officialmcpro32** [comment]
@byteandahalf cool also will you add block renders

**Comment by byteandahalf** [comment]
Eventually.

**Comment by officialmcpro32** [comment]
Byte can you dm me on twitter

**Comment by officialmcpro32** [comment]
@byteandahalf does float works as variable? Example

float Stealer = Steve;

Gui::DisplayClientMessage<< "Who stole the cake?" << Stealer<< endl?

**Comment by officialmcpro32** [comment]
Oops forgot ;

**Comment by byteandahalf** [comment]
That code doesn't make sense :(

**Comment by officialmcpro32** [comment]
@byteandahalf sorry just wanna learn :(

**Comment by byteandahalf** [comment]
I don't know what you're asking me

**Comment by officialmcpro32** [comment]
@byteandahalf I want to learn c++ I was asking if float is be a variable I saw some thing in a tut like double sided for decimals and int is for whole numbers.

**Comment by officialmcpro32** [comment]
@byteandahalf  the message thing I copied it from
float favNum = 32;
cout << "Number" << favNum << endl;

**Comment by officialmcpro32** [comment]
Also how do I use cin ?

**Comment by RandomAltThingy** [comment]
I may create a cydia repository for mod scripts would you like it there when finished?

**Comment by RandomAltThingy** [comment]
@officialmcpro32 If you wanna learn C++ then google the basics like syntax and basic project structure then look on github and play around with peoples open source code there is some open source MCPE addons on github.
